# CHANGE THIS TO YOUR OWN DATASET
TTS_dataset: PrabalAryal/orpheus_new_dataset

model_name: "canopylabs/orpheus-tts-0.1-pretrained"

# Training Args
epochs: 10
batch_size: 1
number_processes: 1
pad_token: 128263
save_steps: 5000
learning_rate: 3.0e-5

# Naming and paths
save_folder: "orpheus-nl-checkpoints"
project_name: "tuning-orpheus"
run_name: "3e5-0"
